#!/bin/bash
# 配置AWS安全组以支持Isaac Sim WebRTC Livestream

echo "📋 Isaac Sim WebRTC需要的端口："
echo "  - 8899  : WebRTC HTTP服务器"
echo "  - 8011  : WebSocket信令服务器"
echo "  - 47998 : Native流媒体端口（备用）"
echo "  - 49100 : Native信令端口（备用）"
echo ""
echo "🔧 请在AWS控制台配置以下安全组规则："
echo ""
echo "=================================="
echo "入站规则 (Inbound Rules):"
echo "=================================="
echo "1. Type: Custom TCP"
echo "   Port: 8899"
echo "   Source: 0.0.0.0/0 (或您的IP)"
echo "   描述: Isaac Sim WebRTC HTTP"
echo ""
echo "2. Type: Custom TCP"
echo "   Port: 8011"
echo "   Source: 0.0.0.0/0 (或您的IP)"
echo "   描述: Isaac Sim WebSocket"
echo ""
echo "3. Type: Custom TCP"
echo "   Port: 47998"
echo "   Source: 0.0.0.0/0 (或您的IP)"
echo "   描述: Isaac Sim Native Stream"
echo ""
echo "4. Type: Custom TCP"
echo "   Port: 49100"
echo "   Source: 0.0.0.0/0 (或您的IP)"
echo "   描述: Isaac Sim Native Signal"
echo ""
echo "5. Type: Custom TCP"
echo "   Port: 8000"
echo "   Source: 0.0.0.0/0 (或您的IP)"
echo "   描述: Teleop API"
echo ""
echo "=================================="
echo ""
echo "或者使用AWS CLI添加规则："
echo ""
echo "SECURITY_GROUP_ID=<your-sg-id>"
echo ""
echo "aws ec2 authorize-security-group-ingress \\"
echo "  --group-id \$SECURITY_GROUP_ID \\"
echo "  --ip-permissions \\"
echo "  IpProtocol=tcp,FromPort=8899,ToPort=8899,IpRanges='[{CidrIp=0.0.0.0/0,Description=\"Isaac WebRTC HTTP\"}]' \\"
echo "  IpProtocol=tcp,FromPort=8011,ToPort=8011,IpRanges='[{CidrIp=0.0.0.0/0,Description=\"Isaac WebSocket\"}]' \\"
echo "  IpProtocol=tcp,FromPort=47998,ToPort=47998,IpRanges='[{CidrIp=0.0.0.0/0,Description=\"Isaac Native Stream\"}]' \\"
echo "  IpProtocol=tcp,FromPort=49100,ToPort=49100,IpRanges='[{CidrIp=0.0.0.0/0,Description=\"Isaac Native Signal\"}]'"
echo ""
echo "=================================="
echo "验证步骤："
echo "=================================="
echo ""
echo "1. 在EC2上检查端口监听："
echo "   netstat -tuln | grep -E '8899|8011|47998|49100'"
echo ""
echo "2. 从本地测试连接："
echo "   curl http://<EC2_IP>:8899"
echo ""
echo "3. 访问WebRTC界面："
echo "   http://<EC2_IP>:8899/streaming/webrtc-client/"
echo ""
